widgets:
    # Profile widget configurations
    - # Where should the widget be placed, left sidebar or right sidebar
      position: left
      type: profile
      # Author name
      author: enncy
      # Author title
      author_title: 言小溪(enncy)
      # Author's current location
      location: 中国
      # URL or path to the avatar image
      avatar:
      # Whether show the rounded avatar image
      avatar_rounded: true
      # Email address for the Gravatar
      gravatar:
      # URL or path for the follow button
      follow_link: https://github.com/enncy
      # Links to be shown on the bottom of the profile widget
      social_links:
          Github:
              icon: fab fa-github
              url: https://github.com/enncy
          ZHIHU:
              icon: fab fa-zhihu
              url: https://www.zhihu.com/people/yxx-enncy
          RSS:
              icon: fas fa-rss
              url: /atom.xml
    # Recommendation links widget configurations
    # -
    #     # Where should the widget be placed, left sidebar or right sidebar
    #     position: left
    #     type: links
    #     # Names and URLs of the sites
    #     links:
    #         Hexo: https://hexo.io
    #         Bulma: https://bulma.io
    # Google AdSense unit configurations
    # -
    #     # Where should the widget be placed, left sidebar or right sidebar
    #     position: right
    #     type: adsense
    #     # AdSense client ID
    #     client_id: ''
    #     # AdSense AD unit ID
    #     slot_id: ''
