name: GitHub Pages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      # 清理
      - run: npx hexo clean
      # 创建 nojekyll 文件
      - run: mkdir public
      - run: echo '# 此文件表明不需要 github 去使用 jekyll 构建本分支' >> public/.nojekyll
      # 构建 部署
      - run: npm run deploy
